name: contacts_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>= 3.10.5'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # Router
  go_router: 10.0.0

  # Database
  objectbox: 2.1.0
  objectbox_flutter_libs: any

  # State manager
  flutter_bloc: 8.1.3
  bloc_concurrency: 0.2.2
    
  # Utils
  meta: any
  path: 1.8.3
  path_provider: 2.0.15
  uuid: 3.0.7

  # Logger
  l: 4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2
  build_runner: 2.4.6
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/contacts.json
