// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/feature/contacts/model/contact_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 2093510403859855431),
      name: 'ContactEntity',
      lastPropertyId: const IdUid(10, 3551450578368966175),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6845476623223550215),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6174571896247114519),
            name: 'contactId',
            type: 9,
            flags: 2048,
            indexId: const IdUid(1, 6920068792273928267)),
        ModelProperty(
            id: const IdUid(3, 2477673706258053696),
            name: 'firstName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5586040068522145421),
            name: 'phoneNumber',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7104261844989455389),
            name: 'lastName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 5675960133625132056),
            name: 'streetAddress1',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 7457435282109296770),
            name: 'streetAddress2',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 7180634016401117066),
            name: 'city',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 1616982668454524571),
            name: 'state',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 3551450578368966175),
            name: 'zipCode',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 2093510403859855431),
      lastIndexId: const IdUid(1, 6920068792273928267),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ContactEntity: EntityDefinition<ContactEntity>(
        model: _entities[0],
        toOneRelations: (ContactEntity object) => [],
        toManyRelations: (ContactEntity object) => {},
        getId: (ContactEntity object) => object.id,
        setId: (ContactEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ContactEntity object, fb.Builder fbb) {
          final contactIdOffset = fbb.writeString(object.contactId);
          final firstNameOffset = fbb.writeString(object.firstName);
          final phoneNumberOffset = fbb.writeString(object.phoneNumber);
          final lastNameOffset = object.lastName == null
              ? null
              : fbb.writeString(object.lastName!);
          final streetAddress1Offset = object.streetAddress1 == null
              ? null
              : fbb.writeString(object.streetAddress1!);
          final streetAddress2Offset = object.streetAddress2 == null
              ? null
              : fbb.writeString(object.streetAddress2!);
          final cityOffset =
              object.city == null ? null : fbb.writeString(object.city!);
          final stateOffset =
              object.state == null ? null : fbb.writeString(object.state!);
          final zipCodeOffset =
              object.zipCode == null ? null : fbb.writeString(object.zipCode!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, contactIdOffset);
          fbb.addOffset(2, firstNameOffset);
          fbb.addOffset(3, phoneNumberOffset);
          fbb.addOffset(4, lastNameOffset);
          fbb.addOffset(5, streetAddress1Offset);
          fbb.addOffset(6, streetAddress2Offset);
          fbb.addOffset(7, cityOffset);
          fbb.addOffset(8, stateOffset);
          fbb.addOffset(9, zipCodeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ContactEntity(
              contactId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              firstName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              phoneNumber: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              city: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18),
              lastName: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              state: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20),
              streetAddress1: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              streetAddress2:
                  const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 16),
              zipCode: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 22))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ContactEntity] entity fields to define ObjectBox queries.
class ContactEntity_ {
  /// see [ContactEntity.id]
  static final id =
      QueryIntegerProperty<ContactEntity>(_entities[0].properties[0]);

  /// see [ContactEntity.contactId]
  static final contactId =
      QueryStringProperty<ContactEntity>(_entities[0].properties[1]);

  /// see [ContactEntity.firstName]
  static final firstName =
      QueryStringProperty<ContactEntity>(_entities[0].properties[2]);

  /// see [ContactEntity.phoneNumber]
  static final phoneNumber =
      QueryStringProperty<ContactEntity>(_entities[0].properties[3]);

  /// see [ContactEntity.lastName]
  static final lastName =
      QueryStringProperty<ContactEntity>(_entities[0].properties[4]);

  /// see [ContactEntity.streetAddress1]
  static final streetAddress1 =
      QueryStringProperty<ContactEntity>(_entities[0].properties[5]);

  /// see [ContactEntity.streetAddress2]
  static final streetAddress2 =
      QueryStringProperty<ContactEntity>(_entities[0].properties[6]);

  /// see [ContactEntity.city]
  static final city =
      QueryStringProperty<ContactEntity>(_entities[0].properties[7]);

  /// see [ContactEntity.state]
  static final state =
      QueryStringProperty<ContactEntity>(_entities[0].properties[8]);

  /// see [ContactEntity.zipCode]
  static final zipCode =
      QueryStringProperty<ContactEntity>(_entities[0].properties[9]);
}
